# This file was generated by GoReleaser. DO NOT EDIT.
class Limp < Formula
  desc "limp is a tool which LIMits standard input which has been Piped to it"
  homepage "https://github.com/nderjung/limp/"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nderjung/limp/releases/download/v0.1.1/limp_0.1.1_darwin_amd64.tar.gz"
    sha256 "c051f21db8785cfd7eddbfd4fa8ca275c6868619b5a11de8c9cca977318e2a9a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/nderjung/limp/releases/download/v0.1.1/limp_0.1.1_linux_amd64.tar.gz"
      sha256 "6a064ba88b624ebed50e1792d9935edfb62f2b1ec3c5c41af25e828831033bb3"
    end
  end

  def install
    bin.install "limp"
  end
end
