# This file was generated by GoReleaser. DO NOT EDIT.
class Limp < Formula
  desc "limp is a tool which LIMits standard input which has been Piped to it"
  homepage "https://github.com/nderjung/limp/"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nderjung/limp/releases/download/v0.1.0/limp_0.1.0_darwin_amd64.tar.gz"
    sha256 "1b0b11555c59e11416a08443e0c616c47bf260549c0e3897716d3b2a9759bf22"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/nderjung/limp/releases/download/v0.1.0/limp_0.1.0_linux_amd64.tar.gz"
      sha256 "dfaaf9a8164bff413d596012c792bd2ee3a8f889fb59103eb8b9674634b5e17d"
    end
  end

  def install
    bin.install "limp"
  end
end
