# This file was generated by GoReleaser. DO NOT EDIT.
class Limp < Formula
  desc "limp is a tool which LIMits standard input which has been Piped to it"
  homepage "https://github.com/nderjung/limp/"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nderjung/limp/releases/download/v0.1.1/limp_0.1.1_darwin_amd64.tar.gz"
    sha256 "83a80273a44c92ef444ee0135f95c7fa6ee5bef7463bd0e26319faa0496fe68f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/nderjung/limp/releases/download/v0.1.1/limp_0.1.1_linux_amd64.tar.gz"
      sha256 "04c2970c1fee69538c0e28aa17c538dd6604c96bf73620b025b01925ab3b3d81"
    end
  end

  def install
    bin.install "limp"
  end
end
